apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmxresp-notifications-deployment
  labels:
    app: pmxresp-notifications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pmxresp-notifications
  template:
    metadata:
      labels:
        app: pmxresp-notifications
    spec:
      containers:
      - name: pmxresp-notifications
        image: notifications-pmxresp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10333
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
