apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmxresp-backend-deployment
  labels:
    app: pmxresp-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pmxresp-backend
  template:
    metadata:
      labels:
        app: pmxresp-backend
    spec:
      containers:
      - name: pmxresp-backend
        image: harbor01.un.pemex.com/spar-qa/backend-pmxresp:latest
        imagePullPolicy: Always # Changed imagePullPolicy
        ports:
        - containerPort: 80
          name: http
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["npm", "start", "production"]
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
