apiVersion: v1
kind: Service
metadata:
  name: pmxresp-backend-service
  namespace: ns-gsd-spar-qa01
spec:
  selector:
    app: pmxresp-backend
  ports:
  - port: 80 # Puerto del servicio
    targetPort: 80 # Puerto en el que escucha tu aplicación Node.js
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 172.19.70.24
